dim_accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'dim_accounts'

urlpatterns = [
    url(r'^signup/$',views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

#                        {%csrf_token %}

dim_zip/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from dim_color import views 
from jcwf_data_center import views as jcwf_data_center_views

from .dash_apps.finished_apps import dim_color_datatable 

#app_name = ''

urlpatterns = [
    url('employee/', jcwf_data_center_views.employee_list, name='jcwf_data_center'),
    path('dim_color_upload/', views.simple_upload),
    #path('employee/', jcwf_data_center_views.employee_list, name='jcwf_data_center'),
    #path('employee/', include('jcwf_data_center.urls')),

]
 

secondDashboard/urls.py
# import my_django_app as my_django_app
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

from dim_accounts import views as accounts_views 
from jcwf_data_center import views as jcwf_data_center_views
# from firstUI import views as firstUI_views
from home_page import views as home_page_views
# from my_django_app import views as my_django_app_views
from dim_customer import views as dim_customer_views
from dim_date import views as dim_date_views
from dim_discount import views as dim_discount_views
from dim_product import views as dim_product_views
from dim_product_group import views as dim_product_group_views
from dim_table import views as dim_table_views 
from jcwf_report_credit_analysis import views as jcwf_report_credit_analysis_views 
from fact_sales_order_item import views as fact_sales_order_item_views 
from plotlyDash import views as plotlyDash_views
from test_page import views as test_page_views



urlpatterns = [ 
    path('signup/', accounts_views.signup_view),
    path('admin/', admin.site.urls), 
    # path('upload/', my_django_app_views.simple_upload),
    path('jcwf_data_center/', jcwf_data_center_views.employee_list),
    path('dim_customer/', dim_customer_views.simple_upload),
    path('dim_date/', dim_date_views.simple_upload),
    path('dim_discount/', dim_discount_views.simple_upload),
    path('dim_product/', dim_product_views.simple_upload),
    path('dim_product_group/', dim_product_group_views.simple_upload),
    path('dim_table/', dim_table_views.simple_upload),
    path('jcwf_report_credit_analysis/', jcwf_report_credit_analysis_views.simple_upload),
    path('fact_sales_order_item/', fact_sales_order_item_views.simple_upload),
    path('', include("django.contrib.auth.urls")),
    path('login/', accounts_views.login_view),
    path('logout/', accounts_views.login_view),
    path('plotlyDash/', plotlyDash_views.plotlyDash),
    path('django_plotly_dash/', include('django_plotly_dash.urls')), 

    url('contact_us', home_page_views.contact_us, name = 'contact_us'),
    url('contact_us_2', home_page_views.contact_us_2, name = 'contact_us_2'),
    url('contact_us_submitted', home_page_views.contact_us_submitted, name = 'contact_us_submitted'),
    url('^$', home_page_views.homePage, name = 'home_page'),
    # url('selectCountry', firstUI_views.indiCountryData, name='indiCountryData'),
    # url(r'^my_django_app/', include('my_django_app.urls')),
    # url(r'^firstUI/', include('firstUI.urls')),
    url(r'^employee/', include('jcwf_data_center.urls'), name='jcwf_data_center'),
    path('dim_accounts/', include('dim_accounts.urls')),
    # path('signup/', include('dim_accounts.urls'), name='signup'),

    
    path('jcwf_data_center/', include('jcwf_data_center.urls')),
    path('jcwf_report_credit_analysis/', include('jcwf_report_credit_analysis.urls')),
    path('dim_date/', include('dim_date.urls')),
    path('dim_discount/', include('dim_discount.urls')),
    path('dim_color/', include('dim_color.urls')),
    path('dim_customer/', include('dim_customer.urls')),
    path('dim_product/', include('dim_product.urls')),
    path('dim_product_group/', include('dim_product_group.urls')),
    path('dim_table/', include('dim_table.urls')),
    path('fact_sales_order_item/', include('fact_sales_order_item.urls')),
    path('home_page/', include('home_page.urls')),
    path('home_page/', home_page_views.homePage),
    path('test_page/', include('test_page.urls')),
    path('test_page/', test_page_views.testPage),
    # path('dim_accounts/login/', include('dim_accounts.urls'), name='logout'),
    # path('dim_accounts/logout/', include('dim_accounts.urls'), name='logout'),
    url(r'session_security/', include('session_security.urls')),
]
   

jcwf_data_center/models.py
from django.db import models

# Create your models here.

class Position(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Employee(models.Model):
    fullname = models.CharField(max_length=100)
    
    emp_code = models.CharField(max_length=3)
    mobile = models.CharField(max_length=15)
    position = models.ForeignKey(Position,on_delete=models.CASCADE)

# Use the three commands below to migrate models into database

'''
python manage.py makemigrations jcwf_data_center

python manage.py sqlmigrate jcwf_data_center 0001

python manage.py migrate

'''

jcwf_data_center/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import EmployeeForm
from .models import Employee

from django.contrib.auth.decorators import login_required
from secondDashboard.decorators import unauthenticated_user, allowed_users
# Create your views here.

# USE request.user.get_username() to get username in views

# from django.http import HttpResponseRedirect
# def dimProduct(request):
#     return HttpResponseRedirect("/dim_product")


@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def dim_color(request):
    return redirect(request,'/dim_color')

@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def dim_customer(request):
    return redirect(request,'/dim_customer')


@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def dim_date(request):
    return redirect(request,'/dim_date')

@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def dim_discount(request):
    return redirect(request,'/dim_discount')

@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def dim_product(request):
    return redirect(request,'/dim_product')

@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def dim_product_group(request):
    return redirect(request,'/dim_product_group')

@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def fact_sales_order_item(request):
    return redirect(request,'/fact_sales_order_item')


@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def employee_list(request):
    context = {'employee_list':Employee.objects.all()}
    return render(request, "jcwf_data_center/employee_list.html",context)

@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def employee_form(request, id=0):
    if request.method == 'GET':
        if id == 0:
            form = EmployeeForm() 
        else:
            employee = Employee.objects.get(pk=id)
            form = EmployeeForm(instance=employee)
        return render(request, "jcwf_data_center/employee_form.html", {'form':form})
    else:
        if id == 0:
            form = EmployeeForm (request.POST)
        else:
            employee = Employee.objects.get(pk=id)
            form = EmployeeForm(request.POST, instance = employee)
        if form.is_valid():
            form.save()
        return redirect('')

@login_required(login_url="/accounts/login/")
@allowed_users(allowed_roles=['jcwf_customer_service'])
def employee_delete(request, id):
    employee = Employee.objects.get(pk=id)
    employee.delete()
    return redirect('/employee/list')


'''

def simple_upload(request):
if request.method == 'POST':
    person_resource = PersonResource()
    dataset = Dataset()
    new_persons = request.FILES['myfile']

    imported_data = dataset.load(new_persons.read(),format='xlsx')
    #print(imported_data)
    for data in imported_data:
        print(data[1])
        value = Person(
            data[0],
            data[1],
                data[2],
                data[3]
            )
        value.save()       
    
    #result = person_resource.import_data(dataset, dry_run=True)  # Test the data import

    #if not result.has_errors():
    #    person_resource.import_data(dataset, dry_run=False)  # Actually import now

return render(request, 'input.html')
'''

jcwf_data_center/templates/jcwf_data_center/base.html
<!DOCTYPE html>
<html Lang='en'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width-device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatile" contect="ie=edge">
    <title>Employee Register</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

</head>
<body>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <p>Welcome, {{ user.get_username }}. </p>   
            <p> Report Center</p>
            <li>
                <form class = "logout-link" action = "{% url 'dim_accounts:logout' %}" method ="POST">
                    {%csrf_token %}
                    <button type = "submit">Logout</button>
                </form>
            </li>
            {% else %}

            {% endif %}
        </ul>
    </nav>





    <div class="col-md-4">
        <a href ="{% url 'dim_product'%}" class="btn btn-secondary btn-block btn-lg">
            <i class="fas fa-stream"></i> Product table
        </a>
    </div>
    <div class="col-md-4">
        <a href ="{% url 'dim_product_group'%}" class="btn btn-secondary btn-block btn-lg">
            <i class="fas fa-stream"></i> Product Group table 
        </a>
    </div>
    <div class="col-md-4">
        <a href ="{% url 'dim_customer'%}" class="btn btn-secondary btn-block btn-lg">
            <i class="fas fa-stream"></i> Customer table
        </a>
        
    </div>
    <div class="col-md-4">
        <a href ="{% url 'dim_discount'%}" class="btn btn-secondary btn-block btn-lg">
            <i class="fas fa-stream"></i> Discount table
        </a>
    </div>
    <div class="col-md-4">
        <a href ="{% url 'dim_date'%}" class="btn btn-secondary btn-block btn-lg">
            <i class="fas fa-stream"></i> Date table
        </a>
    </div>
    <div class="col-md-4">
        <a href ="{% url 'dim_color'%}" class="btn btn-secondary btn-block btn-lg">
            <i class="fas fa-stream"></i> Color table
        </a>
    </div>
    <div class="col-md-4">
        <a href ="{% url 'fact_sales_order_item'%}" class="btn btn-secondary btn-block btn-lg">
            <i class="fas fa-stream"></i> Sales order items table
        </a>
    </div>

<!--
    <div class ="container">
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="jumbotron">
                <h1 class="display-4">Employee Register</h1>
                <p class="lead font-italic">Python Django project for implementing CRUD operations</p>
                </p>

                <hr class="my-4">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </div>
-->


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" 
        crossorigin="anonymous"></script>
</body>
 </html>